### ISSUE TITLE
About the overall result [Precision, Recall, F1]

### ISSUE THREAD

**Issue by demianzhang** [LopezGG/NN_NER_tensorFlow#2]
Thanks for your contribution. I am running the code successfully. I wonder whether the reimplementation of the program is approximate to the original paper result F1=91.21% or not.
 [https://github.com/XuezheMax/LasagneNLP]. The Notes.pdf shows four named entity (P,R,F1), not the whole P,R,F1. Look forward to your reply. Many thanks.

**Comment by demianzhang** [comment]
I try to run the Eval.py to test the test_Predictions_41000.txt. I get the same results as the Notes.pdf says. The same P, R, F1 of [ORG,LOC,MISC,PER,O]. however, when I calculate the overall P, R, F1, I get the P=93.55, R=94.04, F1=93.80. Is it true? Many thanks.

**Comment by demianzhang** [comment]
When I run the Eval.py to test the test_Predictions_41000.txt. I got the same results as the Notes.pdf says. However, when I calculate the overall P,R,F1. I got these P=67.40, R=65.88, F1=66.63, which is far from the 91.21...

**Comment by LopezGG** [comment]
How are you calculating  overall P,R,F1

**Comment by demianzhang** [comment]
Thanks for your reply. From the Eval.py line 71. I changed these to calculate overall precision and recall. I also used both of them to calculate F1. I wonder whether it is right. Please check out. 
`keys = act_count.keys()
sum = 0
sum_all = 0
for k in keys:
    if k == 'O':
        continue
    value = correctEntityCount[k] * 100.0 / act_count[k]
    metricValue[k] = value
    print(k + " : " + str(value))
    sum = sum + correctEntityCount[k]
    sum_all = sum_all + act_count[k]
print sum * 100.0 / sum_all`

**Comment by demianzhang** [comment]
Thanks for your reply. I changed the Eval.py line 71 into these to calculate overall precision and recall. I wonder whether it is right. Please check it out.
`keys = act_count.keys()  
sum = 0  
sum_all = 0  
for k in keys:  
    if k == 'O':  
        continue  
    value = correctEntityCount[k] * 100.0 / act_count[k]  
    metricValue[k] = value  
    print(k + " : " + str(value))  
    sum = sum + correctEntityCount[k]  
    sum_all = sum_all + act_count[k]  
print sum * 100.0 / sum_all`

**Comment by demianzhang** [comment]
Thanks for your reply. I changed the Eval.py line 71 into these to calculate overall precision and recall. I wonder whether it is right. Please check it out.
```python
keys = act_count.keys()
match = 0
sum_all = 0
for k in keys:
    if k == 'O':
        continue
    value = correctEntityCount[k] * 100.0 / act_count[k]
    metricValue[k] = value
    print(k + " : " + str(value))
    match = match + correctEntityCount[k]
    sum_all = sum_all + act_count[k]
print match * 100.0 / sum_all
```

**Comment by LopezGG** [comment]
Why are you using 
```
 if k == 'O':
        continue
```

**Comment by demianzhang** [comment]
When I run the tagger repo [tagger](https://github.com/glample/tagger) , which F1 should be 90.94% according to the paper, I get these on CoNLL-2003 eng.testb:

![image](https://user-images.githubusercontent.com/13177646/27618310-0d921bc6-5bee-11e7-9322-1640f5fa2ec8.png)

The code is wrote in Theano. The corpus is CoNLL-2003, format is IOB. 
Many thanks to your tensorflow reimplementation. I learn a lot from it.

**Comment by LopezGG** [comment]
Thanks @demianzhang. Let me look into it over the weekend
