### ISSUE TITLE
about the NER tagging scheme(BIO-1,BIO-2,BIOES)

### ISSUE THREAD

**Issue by egrcc** [LopezGG/NN_NER_tensorFlow#5]
Hi,
I have a problem with the tagging scheme. In your sample data(https://github.com/LopezGG/NN_NER_tensorFlow/tree/master/Sample_Data), the scheme is the BIOES, but the data I find(https://github.com/glample/tagger/tree/master/dataset) is BIO-1 scheme. Where can I find the BIOES version of CoNLL-2003 dataset? Thanks~

**Comment by LopezGG** [comment]
Sorry.  I believe it you get Conll under NDA. I am not sure where i got the files from. I did this project around 6 months ago.

**Comment by caoxu915683474** [comment]
I have the same problem with him, can you sent the data set to me ?I will appreciate for your help! 18222953809@163.com

**Comment by udion** [comment]
I'm facing the same problem, can you please point to BIOES version or send it to me uddeshya.upa@gmail.com

**Comment by udion** [comment]
@caoxu915683474 were you able to get BIOES format?

**Comment by sunsonhu** [comment]
@caoxu915683474  I have the save problem with you, have you got the dataset in BIOES version? Thank you for your help!  sunsonhu@163.com

**Comment by caoxu915683474** [comment]
@udion  see this notebook the trans format code is in it .https://github.com/jayavardhanr/End-to-end-Sequence-Labeling-via-Bi-directional-LSTM-CNNs-CRF-Tutorial/blob/master/Named_Entity_Recognition-LSTM-CNN-CRF-Tutorial.ipynb

**Comment by udion** [comment]
@caoxu915683474 thanks!
