### ISSUE TITLE
eval question

### ISSUE THREAD

**Issue by ttslr** [LopezGG/NN_NER_tensorFlow#7]
Thank you very much for your code！

I run the Eval.py  on the  “sampleData/test_predictions_41000.txt”

But the result does not seem to be very high  

![ner9](https://user-images.githubusercontent.com/25268285/32422856-cbd46e62-c2dd-11e7-9d7b-95deb0f4e3e0.png)

How is the result  (F1: 91.21  )in the paper obtained?

Thank you very much!!
Best Regards!

**Comment by LopezGG** [comment]
O has high P/R (98) . The score they report was overall not subdivided by type ( eg ORG,MISC and LOC). you  might want to try (weighted) averaging. I have not tried that as yet. Do try and let me know.

**Comment by Jong-Won** [comment]
@LopezGG 
In my opinion, the NE overall F1 is calculated by:
F1 = 2P*R/(P+R)
the overall precision is calculated by:
 #correct NEs in result  / #total NEs in result
they have already not included tag "O" when overall F1
